export const ADD_GATE = 'ADD_GATE';
export const DELETE_GATE = 'DELETE_GATE';
export const UPDATE_GATE_POSITION = 'UPDATE_GATE_POSITION';
export const SET_CURSOR_POSITION = 'SET_CURSOR_POSITION';
export const TOGGLE_GRID = 'TOGGLE_GRID';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const DELETE_CONNECTION = 'DELETE_CONNECTION';
export const TOGGLE_CONNECT_MODE = 'TOGGLE_CONNECT_MODE';