export const ADD_GATE = 'ADD_GATE';
export const DELETE_GATE = 'DELETE_GATE';
export const UPDATE_GATE_POSITION = 'UPDATE_GATE_POSITION';
export const SET_CURSOR_POSITION = 'SET_CURSOR_POSITION';
export const TOGGLE_GRID = 'TOGGLE_GRID';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const DELETE_CONNECTION = 'DELETE_CONNECTION';
export const TOGGLE_CONNECT_MODE = 'TOGGLE_CONNECT_MODE';
export const TOGGLE_DELETE_MODE = 'TOGGLE_DELETE_MODE';

export const CHANGE_STATUS = 'CHANGE_STATUS';
export const ADD_INPUTGATE = 'ADD_INPUTGATE';
export const ADD_OUTPUTGATE = 'ADD_OUTPUTGATE';
export const ADD_NOTGATE = 'ADD_NOTGATE';

export const SET_HOVERED_ELEMENT = 'SET_HOVERED_ELEMENT';
export const SET_USER_STATE = 'SET_USER_STATE';
export const UPDATE_CONNECTION_POSITION = 'UPDATE_CONNECTION_POSITION';